name: Plugin Evaluation
on:
  push:
    branches: [main]
  pull_request:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/action
        with:
          config-path: plugin-eval.yaml
          layers: 'static unit integration'
        env:
          ES_URL: ${{ secrets.ES_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
